<?php

namespace App\Doctrine\Query;

use Doctrine\ORM\Query\AST\FromClause;
use Doctrine\ORM\Query\SqlOutputWalker;
use Symfony\Component\DependencyInjection\Attribute\Exclude;

/**
 * Adds MySQL-specific "FORCE INDEX" statement into SQL query
 * generated by Doctrine ORM query builder.
 *
 * Example usage:
 * ```
 * $query = $queryBuilder->getQuery();
 *
 * $query->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, MysqlForceIndexWalker::class);
 * $query->setHint(MysqlForceIndexWalker::HINT_FORCE_INDEX, 'index_name_here');
 *
 * $result = $query->getResult();
 * ```
 */
#[Exclude]
class MysqlForceIndexWalker extends SqlOutputWalker
{
    public const HINT_FORCE_INDEX = self::class . '.HINT_FORCE_INDEX';

    public function walkFromClause(FromClause $fromClause): string
    {
        $result = parent::walkFromClause($fromClause);

        $forceIndex = $this->getQuery()->getHint(self::HINT_FORCE_INDEX);
        if ($forceIndex) {
            $result = preg_replace('#(\bFROM\s*\w+\s*\w+)#', '\1 FORCE INDEX (' . $forceIndex . ')', $result);
        }

        return $result;
    }
}
